/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "teste.h"


void
operacoes_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  n;
	int  *result_2;
	int  *result_3;


	printf("digite o numero:");
	scanf("%d",&n);

	result_1 = sucessor_1(&n, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = antecessor_1(&n, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = quadrado_1(&n, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("retorno dos valores remotos:");
	printf("sucessor:%d",*result_1);
	printf("antecessor:%d",*result_2);
	printf("quadrado:%d",*result_3);

}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	operacoes_1 (host);
exit (0);
}
