/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "teste.h"

int *
sucessor_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	result = *argp+1;
	/*
	 * insert server code here
	 */

	return &result;
}

int *
antecessor_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	result = *argp - 1;
	/*
	 * insert server code here
	 */

	return &result;
}

int *
quadrado_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	result = (*argp) * (*argp);
	/*
	 * insert server code here
	 */

	return &result;
}
