/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "exemplo.h"


void
operacoes_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  sucessor_1_arg;
	int  *result_2;
	int  antecessor_1_arg;
	int  *result_3;
	int  quadrado_1_arg;
	double  *result_4;
	int  raiz_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, operacoes, operacoes_ORIG, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sucessor_1(&sucessor_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = antecessor_1(&antecessor_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = quadrado_1(&quadrado_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = raiz_1(&raiz_1_arg, clnt);
	if (result_4 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	operacoes_1 (host);
exit (0);
}
