/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pontos.h"


void
exemplo_1(char *host, struct ponto p, struct ponto q)
{
	CLIENT *clnt;
	double  *d;
	dois_pontos  pontos;
	struct ponto  *np;

	clnt = clnt_create (host, exemplo, exemplo_v1, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	pontos.p1 = p;
	pontos.p2 = q;

	d = distancia_1(&pontos, clnt);
	if (d == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	np = soma_1(&pontos, clnt);
	if (np == (struct ponto *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	clnt_destroy (clnt);
	printf("ditancia dos pontos:%lf\n",*d);
	printf("soma dos pontos:(%lf,%lf)\n",np->x,np->y);
}


int
main (int argc, char *argv[])
{
	char *host;
	struct ponto p1, p2;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	printf("digite as coordenada x e y do ponto 1:\n");
	scanf("%lf",&p1.x);
	scanf("%lf",&p1.y);
	printf("digite a coordenada x e y do ponto 2:\n");
	scanf("%lf",&p2.x);
	scanf("%lf",&p2.y);
	

	host = argv[1];
	exemplo_1 (host, p1, p2);
exit (0);
}
