/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pontos.h"

bool_t
xdr_ponto (XDR *xdrs, ponto *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dois_pontos (XDR *xdrs, dois_pontos *objp)
{
	register int32_t *buf;

	 if (!xdr_ponto (xdrs, &objp->p1))
		 return FALSE;
	 if (!xdr_ponto (xdrs, &objp->p2))
		 return FALSE;
	return TRUE;
}
