/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ops_remotas.h"


void
operacoes_1(char *host)
{
	CLIENT *clnt;
	int  *suc, *ant, *q, *rq;
	int  sucessor_1_arg;
	int  antecessor_1_arg;
	int  quadrado_1_arg;
	int  raiz_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, operacoes, operacoes_ORIG, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	suc = sucessor_1(&sucessor_1_arg, clnt);
	if (suc == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	ant = antecessor_1(&antecessor_1_arg, clnt);
	if (ant == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	q = quadrado_1(&quadrado_1_arg, clnt);
	if (q == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	rq = raiz_1(&raiz_1_arg, clnt);
	if (rq == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("sucessor %d\nantecessor %d\nquadrado %d\n raiz quadrada %lf\n",)
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	operacoes_1 (host);
exit (0);
}
