/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "exemplo.h"


void
exemplo_1(char *host)
{
	CLIENT *clnt;
	float  *result_soma;
	dados_soma  args_soma;

#ifndef	DEBUG
	clnt = clnt_create (host, exemplo, soma_remota, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("digite o primeiro valor:");
	scanf("%f",&args_soma.a);
	printf("digite o segundo valor:");
	scanf("%f",&args_soma.b);
	result_soma = soma_1(&args_soma, clnt);
	if (result_soma == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("resultado calculado no servidor: %f\n",*result_soma);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	exemplo_1 (host);
exit (0);
}
