/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EXEMPLO_H_RPCGEN
#define _EXEMPLO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dados_soma {
	float a;
	float b;
};
typedef struct dados_soma dados_soma;

#define exemplo 0x11111
#define soma_remota 1

#if defined(__STDC__) || defined(__cplusplus)
#define soma 1
extern  float * soma_1(dados_soma *, CLIENT *);
extern  float * soma_1_svc(dados_soma *, struct svc_req *);
extern int exemplo_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define soma 1
extern  float * soma_1();
extern  float * soma_1_svc();
extern int exemplo_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dados_soma (XDR *, dados_soma*);

#else /* K&R C */
extern bool_t xdr_dados_soma ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EXEMPLO_H_RPCGEN */
