/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "exemplo.h"

bool_t
xdr_dados_soma (XDR *xdrs, dados_soma *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}
